# Generated by Django 2.0.3 on 2018-03-27 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buysell', '0004_auto_20180324_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('date_posted', models.DateTimeField(verbose_name='Posted date')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buysell.Account')),
            ],
        ),
        migrations.CreateModel(
            name='SellPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.IntegerField(default=0)),
                ('photo', models.FileField(upload_to='documents/')),
                ('location', models.CharField(max_length=200)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buysell.Account')),
            ],
        ),
    ]
