# Generated by Django 2.0.3 on 2018-03-28 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buysell', '0006_auto_20180328_0815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellpost',
            old_name='pub_date',
            new_name='date_posted',
        ),
    ]
