# Generated by Django 2.0.3 on 2018-04-02 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buysell', '0007_auto_20180328_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('time_sent', models.DateTimeField(verbose_name='time sent')),
                ('receiver', models.CharField(max_length=200)),
                ('post_identifier', models.IntegerField(blank=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buysell.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Received',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('time_sent', models.DateTimeField(verbose_name='time sent')),
                ('sender', models.CharField(max_length=200)),
                ('post_identifier', models.IntegerField(blank=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buysell.Account')),
            ],
        ),
    ]
