# Generated by Django 2.0.3 on 2018-04-03 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buysell', '0009_auto_20180403_0932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='received',
            old_name='receiver',
            new_name='publisher',
        ),
        migrations.RenameField(
            model_name='sent',
            old_name='sender',
            new_name='publisher',
        ),
    ]
