# Generated by Django 2.0.3 on 2018-04-03 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buysell', '0010_auto_20180403_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buypost',
            name='price',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sellpost',
            name='amount',
            field=models.CharField(max_length=200),
        ),
    ]
