# Generated by Django 2.0.3 on 2018-04-14 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buysell', '0014_auto_20180413_0647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buypost',
            name='time_diff',
        ),
    ]
