# Generated by Django 2.0.3 on 2018-04-16 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buysell', '0016_auto_20180414_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='received',
            name='post_identifier',
        ),
        migrations.RemoveField(
            model_name='sent',
            name='post_identifier',
        ),
    ]
