# Generated by Django 2.0.3 on 2018-04-16 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buysell', '0017_auto_20180416_0803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='pub_date',
            new_name='date_posted',
        ),
    ]
