# Generated by Django 2.0.3 on 2018-04-16 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buysell', '0018_auto_20180416_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='buy_post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='buysell.Buypost'),
        ),
        migrations.AddField(
            model_name='comment',
            name='date_posted',
            field=models.DateTimeField(default=None, verbose_name='date commented'),
        ),
        migrations.AddField(
            model_name='comment',
            name='sell_post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='buysell.Sellpost'),
        ),
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
