# Generated by Django 2.0.3 on 2018-04-16 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buysell', '0019_auto_20180416_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buycomment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('date_posted', models.DateTimeField(verbose_name='date commented')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buysell.Buypost')),
            ],
        ),
        migrations.CreateModel(
            name='Sellcomment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('date_posted', models.DateTimeField(verbose_name='date commented')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buysell.Sellpost')),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='buy_post',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='sell_post',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
